### ISSUE TITLE
sbcl Linux port

### ISSUE THREAD

**Issue by kaveh808** [kaveh808/kons-9#14]
Port the system to sbcl/Linux/OpenGL.

**Comment by loskool** [comment]
[FYI]  I tried the commit 4f0b793 in the merge-ccl-sbcl branch this morning and I can run the code in sbcl/demo.lisp just fine!

I'm on debian 11, testing. I'm using sbcl 2.2.5

**Comment by omarbassam88** [comment]
I can confirm that the code in the branch `merge-sbcl-macos` is working on Linux. Except of course for the parts in the demo that reference Disk Files which I think should either be included in the repo with relative paths rather than absolute ones or at least point the user to how to get those models. 

The viewport navigation is not working though. I don't know if it was done with COCOA and needs to be replaced now with a cross platform GUI.

**Comment by kaveh808** [comment]
That is an older branch. We're working a new one as we speak.

If you can't wait, grab a copy of the `pruning-ccl` branch. Navigation, animation, and window resizing are working.

Yes, I will be cleaning up the demos, including adding a data directory.

**Comment by omarbassam88** [comment]
Ok, I just tried it now. It's also working. But still viewport key-bindings are not working (probably because you are using [option] and [command] keys which is a Mac Only keys ( I tried using [Alt] and [Ctrl] but still doesn't work . Also, animation using (space) is not working. The viewport toggles work just fine. And I know that my input is well detected because it's being prited correctly in the REPL.

**Comment by omarbassam88** [comment]
Sorry my bad, it's now working perfectly. Only, one issue, We need include `:control` instead of `:super` key when on non-Mac inside the function `mouse-dragged`. 
```lisp

((eq :control *current-mouse-modifier*)
  (incf *cam-fwd-dist* (* 0.1 dx)))

```

**Comment by kaveh808** [comment]
Cool. Thanks for testing. I'll make the change.
