### ISSUE TITLE
Add start and end times for scene animation.

### ISSUE THREAD

**Issue by kaveh808** [kaveh808/kons-9#54]
Necessary for hierarchical motions.

**Comment by JMC-design** [comment]
I've been thinking that animators and animations should be separate.  With the animator assigning the animation to one or more shapes which can constrain the animation within their ranges of motion.
I had a similar  'animator' for 2d stuff before covid, and haven't thought of it since.  I also made use of this library https://github.com/vydd/easing

**Comment by kaveh808** [comment]
Replying here: https://github.com/kaveh808/kons-9/issues/42
